name: "Setup"
description: "Setup go, go-task"
inputs:
  go-version-file:
    description: "Path to go.mod"
    required: true
  task-version:
    description: "Version of go-task"
    required: false
    default: "3.x"
  install-linter:
    description: "Install linters"
    required: false
    default: "false"
  token:
    description: "GitHub token"
    required: true
runs:
  using: "composite"
  steps:
    - name: "Setup Go"
      uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4
      with:
        go-version-file: ${{ inputs.go-version-file }}
      
    - name: "Install go-task"
      uses: arduino/setup-task@b91d5d2c96a56797b48ac1e0e89220bf64044611 # v2
      with:
        version: ${{ inputs.task-version }}
        repo-token: ${{ inputs.token }}
        
    - name: "Install linters"
      if: ${{ inputs.install-linter == 'true' }}
      shell: bash
      run: task back:install:linter
