version: "3"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  dev:
    desc: Run development server
    cmds:
      - bun run dev

  build:
    desc: Build for production
    cmds:
      - bun run build

  preview:
    desc: Preview production build
    cmds:
      - bun run preview

  lint:
    desc: Run linter
    cmds:
      - bun run lint

  install:
    desc: Install dependencies
    cmds:
      - bun install

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist/
      - rm -rf node_modules/.vite

  deps:update:
    desc: Update dependencies
    cmds:
      - bun update

  deps:audit:
    desc: Audit dependencies for vulnerabilities
    cmds:
      - bun audit

  deps:fix:
    desc: Fix dependency vulnerabilities
    cmds:
      - bun audit --fix
