version: '3'

includes:
  back: 
    taskfile: ./backend/taskfile.yml
    dir: ./backend
  front: 
    taskfile: ./frontend/taskfile.yml
    dir: ./frontend

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  db:up:
    desc: Start database and run migrations
    cmds:
      - task copy:env:optional
      - docker compose up -d migrator

  db:down:
    desc: Stop database and clean up
    cmds:
      - docker compose down postgres

  copy:env:
    desc: Copy default env vars
    cmds:
      - cp .env.sample .env
    silent: false

  copy:env:optional:
     desc: Ensure .env exists
     cmds:
      - |
        if [ ! -f .env ]; then
          echo ".env not found, copying from .env.sample"
          cp .env.sample .env
        else
          echo ".env already exists"
        fi