version: '3'

tasks:
  default:
    desc: "Show available tasks"
    cmds:
      - go-task --list-all

  lint:
    desc: "Run golangci-lint"
    dir: backend
    deps: [install:lint]
    cmds:
      - echo "Running linters..."
      - golangci-lint run
  
  test:unit:
    desc: "Run unit tests"
    dir: backend
    cmds:
      - echo "Running unit tests..."
      - go test ./... -v -tags=unit

  install:lint:
    desc: "Install golangci-lint"
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest