version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  lint:
    desc: Run local linter config 
    cmds:
      - golangci-lint run

  run:
    desc: Run in debug mode
    cmds:
      - go run cmd/main.go

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
  
  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./... -v -tags=unit

  install:
    desc: Install dependencies
    cmds:
      - task: install:linter
      - task: install:swagger

  install:linter:
    desc: Install linter
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

  install:swagger:
    desc: Install Swagger tools
    cmds:
      - go install github.com/swaggo/swag/cmd/swag@v1.8.12

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  vendor:
    desc: Create vendor directory
    cmds:
      - go mod vendor

  download:
    desc: Download dependencies
    cmds:
      - go mod download

  install:migrator:
    desc: Install migrator
    cmds:
      - go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.2

  
  db:migrate:up:
    desc: Run migrations
    cmds:
      - migrate -database "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" -path db/migrations up

  db:migrate:down:
    desc: Run database migrations down
    cmds:
      - migrate -database "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable" -path db/migrations down

  db:migrate:create:
    desc: Create new migration file
    cmds:
      - go run -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.2 create -ext sql -dir ./db/migrations -seq {{.CLI_ARGS}}

  swagger:generate:
    desc: Generate Swagger documentation
    cmds:
      - go run github.com/swaggo/swag/cmd/swag@v1.8.12 init -g cmd/main.go -o ./docs

  swagger:serve:
    desc: Serve Swagger documentation locally
    cmds:
      - echo "Swagger documentation will be available at http://localhost:8080/swagger/index.html"
      - echo "Make sure the server is running with 'task run'"

  swagger:validate:
    desc: Validate Swagger annotations
    cmds:
      - go run github.com/swaggo/swag/cmd/swag@v1.8.12 fmt -g cmd/main.go
      - go run github.com/swaggo/swag/cmd/swag@v1.8.12 init -g cmd/main.go -o ./docs --parseDependency --parseInternal
