version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list-all

  lint:
    desc: Run local linter config 
    cmds:
      - golangci-lint run

  run:
    desc: Run in debug mode
    cmds:
      - go run cmd/main.go

  test:
    desc: Run all tests
    cmds:
      - task: test:unit
  
  test:unit:
    desc: Run unit tests
    cmds:
      - go test ./... -v -tags=unit

  install:
    desc: Install dependencies
    cmds:
      - task: install:linter

  install:linter:
    desc: Install linter
    cmds:
      - go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.1.6

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  vendor:
    desc: Create vendor directory
    cmds:
      - go mod vendor

  download:
    desc: Download dependencies
    cmds:
      - go mod download