name: Deploy Swagger Documentation

on:
  push:
    paths:
      - 'backend/internal/handler/**'
      - 'backend/cmd/main.go'
      - 'backend/docs/**'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'
        
    - name: Install Swagger
      run: go install github.com/swaggo/swag/cmd/swag@v1.8.12
      
    - name: Generate Swagger Docs
      working-directory: ./backend
      run: |
        swag init -g cmd/main.go -o ./docs
        
    - name: Copy HTML template
      run: |
        cp docs/index.html backend/docs/
        
    - name: Setup Pages
      uses: actions/configure-pages@v4
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./backend/docs
        
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
